### ISSUE TITLE
Should be a warning when leaving an overpopulation on the board

### ISSUE THREAD

**Issue by Quuxplusone** [thelast19digitsofpi/homeworlds-live#17]
In game 158, I made an overpopulation at my opponent's homeworld, and then accidentally forgot to catastrophe it before clicking "End turn." Of course this _was_ my fault; but given all the other warning messages, I was surprised that there was no pop-up warning related to leaving an overpopulation on the board. Or maybe there was a warning, and I didn't see it? But I really don't think there was any warning.

(It is _possible_ that with all the other warnings I've become "warning-blind" and clicked through without reading a warning it was trying to give me.)

A more complicated solution to this problem in general would be:

- On each warning message pop-up, put a little set of buttons so that logged-in users can say "Don't unfurl this warning by default (but I can still get to it by clicking 'Warnings')" or "Okay, I don't mind this pop-up" or "Yikes! please go even further and make this situation require an extra click to confirm!" Remember the logged-in user's preference per warning.

If that solution were implemented, I'd turn the "You have unused actions" and "You have no big ship" warnings off, but I'd turn the "You left overpopulations" warning up as high as it would go.

**Comment by thelast19digitsofpi** [comment]
Fixed.
