### ISSUE TITLE
getPieceInStashByType is not a function during Tutorial

### ISSUE THREAD

**Issue by SimonN** [thelast19digitsofpi/homeworlds-live#3]
Played on: https://homeworlds-live2.glitch.me/tutorial#1

Select the Basic Opening Strategy Tutorial. Play several moves to reach the position shown in the screenshot: We have a g3, y2, r1 at home. It's our turn. Click the r1. Click Build R2 here. A popup opens: "Illegal action! e.getPieceInStashByType is not a function".

Expected instead: The r2 build succeeds and I can click End Turn.

No feedback about the rated games yet because nobody else was online to play. :-) Homeworlds Live is a great stab in the correct direction: Live games that don't rely on proprietary chat systems or conference tools. I'm looking forward!

![construct-r2-exception](https://user-images.githubusercontent.com/674969/93812750-56ae4200-fc52-11ea-88d4-f652aa35c9da.png)

**Comment by thelast19digitsofpi** [comment]
I **believe** this has been fixed.

**Comment by SimonN** [comment]
Right, now the r2 can be built without errors. Alternative moves won't trigger the error either. Thanks!
