### ISSUE TITLE
Does the "Star Demolition Defense" tutorial actually have a solution?

### ISSUE THREAD

**Issue by KJFreshly** [thelast19digitsofpi/homeworlds-live#31]
Might not be the appropriate place to leave this, but it _may_ be unintended. There doesn't seem to be an outcome that I can see for this tutorial puzzle that results in a win. To me, this is due to north controlling a g2 and a g3 on separate star systems, leaving no possible way of assessing each threat. If there is a solution that is supposed to work, I cannot see it.

Thank you for your work!

**Comment by thelast19digitsofpi** [comment]
Are you talking about 2.0 or Defense? In Defense, you're not supposed to
"win" per se, only survive your opponent's invasion. I'm not sure what the
g2 and g3 would be useful for, given that you have a yellow monopoly.

**Comment by KJFreshly** [comment]
The Defense tutorial is the one in question.
The reason the g2 and g3 seem important is because if the opponent's red is not captured on my homeworld, the opponent can sacrifice either the g2 or g3 and win next turn by building red. There is no way to destroy both star system 7 and 10 in the first turn to prevent that from happening, so capturing the opponent's r1 is the only move, which is fine.
The tutorial then moves the opponent's r3 to the player's homeworld, and the same scenario is true. There is no way to prevent either the opponent moving the r1 into my homeworld if I capture their r3, or sacrificing the g2 or g3 and building if I don't capture the r3, and again, it's impossible to eliminate both the g2 and g3. I can't find a resolution where neither of these outcomes happen. If the g2 and g3 were on the 'same' star system which could then be destroyed with a catastrophe using my yellow monopoly, then that would make sense.

**Comment by thelast19digitsofpi** [comment]
I'll respond in rot13 because this is sort of a spoiler for that puzzle,
but:
Nggnpxvat gur e1 ba gur svefg ghea vf pbeerpg. Nsgre gung, lbh unir gb or n
yvggyr ovg perngvir.

(I can confirm that the tutorial does work as intended, when you play the
correct actions. It's just a little tricky to find those actions!)

**Comment by KJFreshly** [comment]
This is an absolutely flooring principle to learn. Sorry to bother you with a question about it! Take care and be safe, and thank you for the responses.
