### ISSUE TITLE
Sandbox Replay

### ISSUE THREAD

**Issue by bcurfs** [thelast19digitsofpi/homeworlds-live#4]
Hi,
I just played a sample game in the Sandbox.
It has some cool features: Get Map and Get Log. What do they do?
But then I was trying to change them, and I couldn't. I also tried to Load Log, to be able to see the game after I restarted a new game. But I couldn't. I may not understand how to use it? 

Also, I thought that it might be cool to be able to replay your sandbox game, especially if it's some kind of demo you can share with others, to illustrate certain principles, or just to get pics of your game that you played earlier. (I think that the replay works well for archived games, though).

Thanks,
Bruno.

**Comment by thelast19digitsofpi** [comment]
These are fixed in the new year update.
