### ISSUE TITLE
redirect automatically on completed games 

### ISSUE THREAD

**Issue by davidlwillson** [thelast19digitsofpi/homeworlds-live#8]
wish: For a game that has been completed, instead of warning "game not found" and offering a potentially good link to the archive, just redirect the user and/or give the content.

i.e. When game 105 is a completed game, the app has all the information it needs to just do the right thing with a request for "game 105". Why not just do it, and only stop and warn when the right thing *isn't* obvious?

**Comment by thelast19digitsofpi** [comment]
That's a good idea. I'll probably give a patch for that this weekend.
