### ISSUE TITLE
"Confirm RESIGN" button stays active after resigning

### ISSUE THREAD

**Issue by Quuxplusone** [thelast19digitsofpi/homeworlds-live#9]
<img width="1440" alt="after-resign" src="https://user-images.githubusercontent.com/702021/108610837-d0379100-73a6-11eb-9f55-b5a6072cc328.png">

I used the "Resign" button to resign a game. It worked as expected. But, after the game had successfully ended, the right pane was still asking me to "Confirm RESIGN" or "CANCEL!". Those buttons should really go away at that point (maybe replaced with the text "You have resigned" or something).

The "Offer a Draw" button should probably go away at the end of the game, too.

The "Reset Turn" and "End Turn" buttons should also get grayed out at the end of the game, the same way they're grayed when it's not your turn. (After the game has ended, it's no longer your turn.)

This was in Chrome, just in case the browser matters.

**Comment by thelast19digitsofpi** [comment]
In the latest update, the buttons are removed.
